import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { Sparkles } from 'lucide-react'
import GlassCard from './GlassCard'

const fullInsight = 'Revenue is up 12.5% today driven by strong evening sales at Locations 1 and 2. Inventory velocity for Paracetamol (SKU-2847) is trending 340% above baseline — emergency PO has been triggered. Customer sentiment remains stable at 4.2/5.0. No systemic issues detected across other KPIs.'

export default function AIInsightPanel() {
  const [displayed, setDisplayed] = useState('')
  const [isComplete, setIsComplete] = useState(false)

  useEffect(() => {
    setDisplayed('')
    setIsComplete(false)
    let i = 0
    const interval = setInterval(() => {
      if (i < fullInsight.length) {
        setDisplayed(fullInsight.slice(0, i + 1))
        i++
      } else {
        setIsComplete(true)
        clearInterval(interval)
      }
    }, 15)
    return () => clearInterval(interval)
  }, [])

  return (
    <GlassCard className="p-4">
      <div className="flex items-center gap-2 mb-3">
        <Sparkles size={16} className="text-sentinel-purple" />
        <h3 className="text-sm font-semibold text-sentinel-text-primary">AI Business Summary</h3>
        {!isComplete && (
          <motion.span
            className="w-1.5 h-3 bg-sentinel-purple"
            animate={{ opacity: [1, 0] }}
            transition={{ duration: 0.6, repeat: Infinity }}
          />
        )}
      </div>
      <p className="text-xs text-sentinel-text-secondary leading-relaxed">
        {displayed}
      </p>
      {isComplete && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="mt-3 flex items-center gap-2"
        >
          <span className="text-[10px] text-sentinel-text-muted">Generated by Gemini 2.5 Pro</span>
          <span className="w-1 h-1 rounded-full bg-sentinel-text-muted" />
          <span className="text-[10px] text-sentinel-text-muted">Just now</span>
        </motion.div>
      )}
    </GlassCard>
  )
}
