/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#303542",
        "on-tertiary-fixed": "#001c39",
        "surface-container-high": "#252a36",
        "on-tertiary-container": "#005194",
        "surface-tint": "#3cd7ff",
        "tertiary-container": "#9ec5ff",
        "on-primary-container": "#00586b",
        "secondary": "#cabeff",
        "primary": "#a8e8ff",
        "on-secondary-fixed": "#1c0062",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#4816cb",
        "background": "#0e131f",
        "primary-fixed-dim": "#3cd7ff",
        "tertiary": "#cee0ff",
        "secondary-fixed": "#e6deff",
        "on-surface": "#dee2f3",
        "surface-dim": "#0e131f",
        "outline-variant": "#3c494e",
        "on-secondary-container": "#b9aaff",
        "tertiary-fixed-dim": "#a4c9ff",
        "primary-container": "#00d4ff",
        "on-surface-variant": "#bbc9cf",
        "secondary-container": "#4816cb",
        "surface-container-highest": "#303542",
        "primary-fixed": "#b4ebff",
        "error-container": "#93000a",
        "surface-container": "#1a1f2c",
        "on-tertiary": "#00315d",
        "secondary-fixed-dim": "#cabeff",
        "inverse-on-surface": "#2b303d",
        "on-primary-fixed": "#001f27",
        "surface-container-lowest": "#090e19",
        "surface-bright": "#343946",
        "error": "#ffb4ab",
        "surface-container-low": "#161b27",
        "surface": "#0e131f",
        "outline": "#859398",
        "on-primary": "#003642",
        "tertiary-fixed": "#d4e3ff",
        "inverse-surface": "#dee2f3",
        "on-secondary": "#31009a",
        "on-primary-fixed-variant": "#004e5f",
        "on-background": "#dee2f3",
        "on-error": "#690005",
        "inverse-primary": "#00677e",
        "on-tertiary-fixed-variant": "#004884"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        base: "4px",
        xl: "64px",
        sm: "16px",
        margin: "32px",
        md: "24px",
        xs: "8px",
        lg: "40px",
        gutter: "20px"
      },
      fontFamily: {
        "technical-xs": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "technical-sm": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "technical-xs": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "technical-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}
